// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };





// import "./globals.css";
// import Navbar from "./components/Navbar";

// export default function RootLayout({ children }) {
//   return ( 
//     <html lang="en">
//       <body
//         className={`antialiased`}
//       >
//         {/* <Navbar/>  */}
//          {/* Add the Navbar here */}
//         {children}  {/* This is where the page content will render */}
//       </body>
//     </html>
//   );
// }

































import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "المبتكرون الصغار",
  description: "تم إنشاء هذا التطبيق باستخدام Next.js لتقديم تجربة حديثة وسريعة.",
  icons: {
    icon: "/favicon.ico", // ✅ Path to your favicon in the public folder
    shortcut: "/favicon.ico", // ✅ Optional, for better browser support
    apple: "/favicon.ico", // ✅ Optional, for Apple devices
  },
};

import Navbar from "./components/Navbar";

export default function RootLayout({ children }) {
  return ( 
    <html lang="en">
      <body className="antialiased">
        <Navbar/>  
        {children}  {/* This is where the page content will render */}
      </body>
    </html>
  );
}
